travis:
  secure:
    BINSTAR_TOKEN: dg8xfyTn5i8Bp/Tm2+Sq4rr4FCFPCDCEIe4bLmSJVkjyxY0NXONSLuDbG3Ov/+6SkWcUCxW+QAz+8fQAhKGLehhFxipqeC2XznyLmW2T7hq/poL78l8uFyadKZsgJ5+qIZwvKjAG1ZO1lMUS0fl+f7M5fJmByP6i6nXJ+pm/UOh6iHbkyJBdw4O61Qw7qAM9QOKjihLwbkjxqWE91qXgrUkZqKGUqWvTDVush8GysD4OYRdCO2T5GALxU5TDShKork7SHpMOOsAV2NT4nXs6TsBBDzpg8kH2bdOPlZkud8tB6n9WqyuJ4nMn9CtM/fj7FI6fXhFP7Wdahl9gD5af2bLZpeRLSa1NuuqcjkFB3KoAp2kFFl0ptGBVJPZko6ZynAnOO+zl40jbZqoIixpytWBpqCndGdUOAoRXnB7/2y1fte5DUzb3ydnQQ7z/waHqDBm2BWpxWkXydYD8nb5blcvvr/2t6Gydmg+pOVwTSPbGXCo25dy8sV4d5XCUskjnX4FaOrrj2qLxY8GuQRxlX+JDN+1ppL3K0AB5gCRy+MUelsdP+m6Jy9Px/NWm/91+y/ZNynbGyzEV48G0jl9iU8XHqbseNmdCHYdviuWHRPqqZP0k+n11rbjigMdGqenOcNDSu8XM3IwK6Jqc+Qz+3ayvmuvBcoErP9ZZSGusLe0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
