appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WwOY6h3lGkLniugUS/emKxWnV8q5DE6S5dN14Hf7awZY4bboNOohyav2AX0k+t6CsHJ1lH2xR1USIPxlWVawzTro6lkF5+DlZ2qmoX41U294u0wyh4WobuG2nKqVRZdTj381fKT4iGkKL+x+ogbC+FM8EZt2dzqx84itQN180Y4vJ5orYXJOKofJwU5JzxFmV0FIfI5uUcd1bOiQOe4yd223gmQVfA9pXJvOA3c7AAxpELzvWAvkAtFp95QQpoeK59QlXdH5iTY97o9v6PwH4FjDemjxubC4lDP5vNw9NiOwhozrJaJlBFcDlOeT97k0qdRTlo/oLFnoJmDMn7BirC7WOOC9T2UOAx4AJuwvncqReS1IbkiHlD7+mpQCbGpnyArRRO/ktb/eX2LJ5FfWueY4JXl5XLIoX3rxHGgcYw62AS6G82dsNTAPxUQzG+ZLXsTqMX9ZOOS3Dsfl4fQ0P3UvpGWJjMOIEx6oisqsG5lNuKG53QKBmLR7iBovIzycz+nyf4y4X7b5OFklIm8ZejiKLHECy+dnzI5AU/f3sKbdx6Onyc23ckjihkPuRBjVCQ7WdPhLechBqgz9VtvUu9uOf+qBBs1sI0arnYJXCRwOiTguKugmDucN9Uf3x3uHkI5tZIt68iajnZPDfhfOD1+lYBVBb2Fc+tTdgtR9seI=}
